// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the appropriate FirebaseOptions for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS. '
          'Run `flutterfire configure` to add iOS support.',
        );

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS. '
          'Run `flutterfire configure` to add macOS support.',
        );

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
          'Run `flutterfire configure` to add Linux support.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔹 Web Firebase configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLIQcTzGhnn3SPx0YH_YHt98Pv06W_2N0',
    appId: '1:566272820224:web:7307b61eb09aeb89fc44e5',
    messagingSenderId: '566272820224',
    projectId: 'myapp-a5248',
    authDomain: 'myapp-a5248.firebaseapp.com',
    storageBucket: 'myapp-a5248.firebasestorage.app',
  );

  // 🔹 Android Firebase configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTqsNTZxbDjqwIlbnpLvIUmvxl5ODhlso',
    appId: '1:566272820224:android:c3c42ae086125ba5fc44e5',
    messagingSenderId: '566272820224',
    projectId: 'myapp-a5248',
    storageBucket: 'myapp-a5248.firebasestorage.app',
  );

  // 🔹 Windows Firebase configuration (reuses Web settings)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLIQcTzGhnn3SPx0YH_YHt98Pv06W_2N0',
    appId: '1:566272820224:web:a0ba65c4811f8f1cfc44e5',
    messagingSenderId: '566272820224',
    projectId: 'myapp-a5248',
    authDomain: 'myapp-a5248.firebaseapp.com',
    storageBucket: 'myapp-a5248.firebasestorage.app',
  );
}
